" Little required stuff -------------------- {{{
set encoding=UTF-8 		    " set the encoding
set nocompatible		   	" be Improved, required
filetype off			    " required
filetype plugin on
" }}}

" Plugins -------------------- {{{
"rtp means (r)un (t)ime (p)ath
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/plugged')

Plugin 'VundleVim/Vundle.vim'

" Addons
Plugin 'scrooloose/nerdtree'
Plugin 'yuttie/comfortable-motion.vim' " Smooth scrolling
Plugin 'tpope/vim-surround' " Surroundings
Plugin 'Valloric/YouCompleteMe' 

" Themes
Plugin 'altercation/vim-colors-solarized'
Plugin 'icymind/NeoSolarized'
Plugin 'morhetz/gruvbox' "The best...
Plugin 'vim-python/python-syntax'
Plugin 'junegunn/seoul256.vim'
Plugin 'arcticicestudio/nord-vim'
Plugin 'romainl/flattened'

" Jedi-vim (not that useful actually)
"Plugin 'davidhalter/jedi-vim'

" Searching (<C-P>)
Plugin 'ctrlpvim/ctrlp.vim'

" Airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Git Integration
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

" Commenting lines
Plugin 'vim-scripts/tComment'

" Arduino syntax
Plugin 'sudar/vim-arduino-syntax'

" Note plugin
Plugin 'xolox/vim-notes'
Plugin 'xolox/vim-misc'

" Show code errors
Plugin 'vim-syntastic/syntastic'

" Multiple cursors
Plugin 'terryma/vim-multiple-cursors'

" Auto-closing
Plugin 'cohama/lexima.vim'

" HTML
Plugin 'mattn/emmet-vim'

" Documentation
Plugin 'vim-utils/vim-man'
Plugin 'gauteh/vim-cppman' " cpp
Plugin 'vim-scripts/pydoc.vim'

" LaTeX Plugin (exciting stuff)
Plugin 'lervag/vimtex'

" Markdown style stuff
Plugin 'shime/vim-livedown'


" Test Plugin
"Plugin 'file:///home/monepicor/Projects/VimScript/color-changer'

call vundle#end()
filetype plugin indent on 	" required
" }}}

" Mappings -------------------- {{{
" Leader Mappings
map <Space> <leader>
map <leader>w   :w<CR>
map <leader>q   :q<CR>
map <leader>!   :qa<CR>
map <leader>gs  :Gstatus<CR>
map <leader>= 	 <C-W>=

" NERDTree Mappings
map <leader>nt   :NERDTreeToggle<CR>
map <leader>nf   :NERDTreeFocus<CR>
map <leader>nc   :NERDTreeCWD<CR>

" Edit .vimrc quickly in a split
map <leader>ev   :sp ~/.vimrc<CR>
" Source .vimrc 
map <leader>sv   :source ~/.vimrc<CR>

" Clear Search Highlight
map <leader>csh  :nohlsearch<CR>
" Redraw the screen
map <leader>rd	 :redraw!<CR>

" Easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Easy tab navigations
nnoremap <C-y>   :tabprevious<CR>
nnoremap <C-o>   :tabnext<CR>
" }}}

" Abbreviations -------------------- {{{
iabbrev asim not awesome
iabbrev environmnent environment
" }}}

" Settings [let and set] -------------------- {{{
let g:auto_save = 1 				" Enable auto save on Vim startup
let g:auto_save_in_insert_mode = 0	" Do not save in insert mode

" Reduce gitgutter updatetime
set updatetime=100

" Airline tab thing
let g:airline#extensions#tabline#enabled = 1

syntax on

set autoread								" Auto reload changed files
set nowrap 									" Don't wrap the long lines
set shiftwidth=4 tabstop=4 				 	" Two spaces for tabs
set noswapfile								" Turn off swap files
set hlsearch								" Highlight the search results
set showcmd									" Show commands on status bar

let g:tex_flavor = 'latex'

" Python interpreters
let g:python_host_prog  = '/usr/bin/python2.7'	  " Python 2
let g:python3_host_prog = '/usr/bin/python3.7'  " Python 3
" to disable
"let g:loaded_python_provider = 1
"let g:loaded_python3_provider = 1


" Latex neovim support
let g:vimtex_compiler_progname = 'nvr'

" }}}

" Persistent undo -------------------- {{{
set undodir=~/.vim/undo
set undofile
set undolevels=1000
set undoreload=10000
" }}}

" Interface -------------------- {{{
set number relativenumber 				" Enable line numbers
set scrolloff=10						" Leave 10 lines of buffer when scrolling
set sidescrolloff=10					" Leave 10 characters of horizontal buffer when scrolling
" }}}

" Look & Feel ;) -------------------- {{{
set background=dark
colorscheme gruvbox

" Airline theme
let g:airline_theme='badwolf'

"set guifont=DroidSansMono\ Nerd\ Font\ 11

" Showcase comments in italics
highlight Comment cterm=italic gui=italic

" Make the python code look pretty
let python_highlight_all=1

" }}}

" Vimscript file settings -------------------- {{{
augroup filetype_vim
	autocmd!
	autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

" Push yourself to learn -------------------- {{{
" Disable h,l and use w,e,b,g_,0,$,^ instead
nnoremap h <nop>
nnoremap l <nop>
vnoremap h <nop>
vnoremap l <nop>
" }}}

" Syntastic Settings -------------------- {{{
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
" }}}

" Little Ideas -------------------- {{{
" Make a command that changes colorcheme with arrow keys
" Dictionary Plugin
" }}}

" Testing -------------------- {{{
"let g:jedi#auto_vim_configuration=0
"let g:jedi#popup_on_dot=1
"let g:jedi#popup_select_first=0
let g:gitgutter_enabled = 1
fun! ProfileStart(...)
	if a:0 && a:1 != 1
		let g:profile_file = a:1
	else
		let g:profile_file = '/tmp/vim'.getpid().'.'.reltimestr(reltime())[-4:].'profile.txt'
		if a:0 < 2 || a:2
			@* = g:profile_file
		endif
	endif
	echom "Profiling into" g:profile_file
	exec 'profile start '.g:profile_file
	profile! file **
	profile  func *
endfun
if len(get(g:, 'profile', ''))
	call ProfileStart(g:profile)
endif
if 0
	call ProfileStart(1, 0)
endif
" }}}

" Example Group -------------------- {{{
" You know what, use built-in command to
" \ make groups you dummy!
" }}}

